package com.example.herouard.piedpiper;

import io.realm.RealmObject;
import io.realm.annotations.Ignore;
import io.realm.annotations.PrimaryKey;

/**
 * Created by ha613438 on 05/12/2016.
 */

public class BDD_Score extends RealmObject {

    private int score;

    @PrimaryKey
    private int id;

    @Ignore
    private int sessionId;

    // Standard getters & setters generated by your IDE…
    public int getId() { return id; }
    public void setId(int id) { this.id = id; }
    public int getScore() { return score; }
    public void setScore(int score) { this.score = score; }
    public int getSessionId() { return sessionId; }
    public void setSessionId(int sessionId) { this.sessionId = sessionId; }

}

